# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoIn1hr < Formula
  desc ""
  homepage "https://github.com/VikasPoddar/homebrew-go-in-1hr"
  version "0.0.2-rc-2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/VikasPoddar/go-in-1hr/releases/download/v0.0.2-rc-2/go-in-1hr_Darwin_x86_64.tar.gz"
      sha256 "9c6388cda38cb6f7de0f88d6e343a012c6f934ba5ddf0c5d1800948e6ef49973"

      def install
        bin.install "go-in-1hr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/VikasPoddar/go-in-1hr/releases/download/v0.0.2-rc-2/go-in-1hr_Darwin_arm64.tar.gz"
      sha256 "eddca9e3b3bb32293716717dc07a524533ede623a6c71bc57642aae44ea1d296"

      def install
        bin.install "go-in-1hr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/VikasPoddar/go-in-1hr/releases/download/v0.0.2-rc-2/go-in-1hr_Linux_x86_64.tar.gz"
        sha256 "0f35da7c19ee222122f2c7274f095dbdc65d7291453ad9df73de5f88e94d8642"

        def install
          bin.install "go-in-1hr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/VikasPoddar/go-in-1hr/releases/download/v0.0.2-rc-2/go-in-1hr_Linux_arm64.tar.gz"
        sha256 "8fa63af9d7ab6757bc55cbb22ee9a3e22ef348dc3043302f2359a5a7242d5d8d"

        def install
          bin.install "go-in-1hr"
        end
      end
    end
  end
end
